#!/usr/bin/env bash
# Transfers a file from our client to a server

# Check if all required parameters are passed
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Assign parameters to variables
  file_path=$1
  server_ip=$2
  username=$3
  ssh_key=$4

  # Transfer the file using scp
  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~
fi
