#!/usr/bin/env bash
# Install nginx web server

# Update and install app
sudo apt-get  update
sudo apt-get  install -y nginx

# path for installation
mkdir /etc/nginx/html

# Creating a sample page
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /etc/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
}" > /etc/nginx/sites-available/default
# Restarting the ngixx
service nginx restart
