#!/usr/bin/env bash
# install and configure HAproxy service

sudo apt-get update -y
sudo apt-get install haproxy -y
echo "
frontend permac
	bind *:80
	mode http
	default_backend permac_back
	balance roundrobin
	server 129553-web-01 54.90.6.108:80 check
	server 129553-web-02 54.87.212.53:80 check
" >> /etc/haproxy/haproxy.cfg
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy
sudo service haproxy restart
