#!/bin/bash

# Display listening ports and associated PID and program name
echo "Listening Ports and Associated PID and Program Name:"
netstat -tulpn | grep LISTEN | awk '{print $4 " " $7}' | while read line;
do
    port=$(echo $line | cut -d: -f2)
    pid=$(echo $line | awk '{print $NF}' | cut -d/ -f1)
    name=$(ps -p $pid -o comm=)
    echo "$port $pid $name"
done

