#!/usr/bin/env bash
# Set the trap to print things when it  receives a SIGTERM,SIGINT, SIGQUIT or` SIGTERM signal
# Set the trap to print things when it  receives a SIGTERM,SIGINT, SIGQUIT or` SIGTERM signal
# Set the trap to print things when it  receives a SIGTERM,SIGINT, SIGQUIT or` SIGTERM signal

trap "echo 'I hate the kill commande me?!'; rm /var/run/myscript.pid; exit"  SIGTERM
trap "echo 'Y U no love me?!'"  SIGINT 
trap "rm /var/run/myscript.pid; exit" SIGQUIT || SIGTERM 
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
