#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" upon receiving a SIGTERM
# Displays "Y U no love me?!" upon receiving a SIGINT
# Deletes the file /var/run/holbertonscript.pid and terminates upon
# receiving a SIGQUIT or SIGTERM
echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit"  SIGTERM
trap "echo 'Y U no love me?!'"  SIGINT 
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT || SIGTERM 
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
