#!/usr/bin/env bash
# a bash script to install the ufw firewall and setup a few rules on web-01.
sudo apt-get update
sudo apt-get install ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw enable

