#!/usr/bin/env bash
#a script to test my knowledge of nginx

sudo apt-get update
sudo apt-get install -y nginx
# making the directory
mkdir /etc/nginx/html

content="<h1>This was just to test the innner Workings of the server</h1>"

sudo cp /etc/nginx/sites-available/default etc/nginx/html/About.html
echo $content > /etc/nginx/html/About.html

service nginx restart
